# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flowise-docker-app

on:
    push:
        branches:
            - xmacna
    workflow_dispatch:

jobs:
    build:
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to registry
              uses: docker/login-action@v2
              with:
                  registry: https://xmacna.azurecr.io/
                  username: ${{ secrets.AzureAppService_ContainerUsername_dc4c44b92ef6494fa7e3a254fefeae98 }}
                  password: ${{ secrets.AzureAppService_ContainerPassword_4ce82f5391e746fc96e9452e11432d05 }}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: xmacna.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc4c44b92ef6494fa7e3a254fefeae98 }}/flowise-xmacna-2:${{ github.sha }}
                  file: ./Dockerfile

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: 'flowise-docker-app'
                  slot-name: 'production'
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_0346da7745094323a465510af5e2a181 }}
                  images: 'xmacna.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc4c44b92ef6494fa7e3a254fefeae98 }}/flowise-xmacna-2:${{ github.sha }}'
